config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "calculates#index"
  resources :calculates
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calclate.rb
class Calclate < ApplicationRecord
  validates :weight, presence: true
  validates :activity_time, presence: true

  # 体重と運動時間から必要な水分量を計算する
  def calculate_water_amount
    water_amount = self.weight * self.activity_time * 5 * 0.8
    rounded_water_amount = water_amount.to_i
    return rounded_water_amount
  end
  
#必要な水分量から500mlのペットボトルの本数を計算する
  def calculate_water_bottles
    water_amount = calculate_water_amount
    bottles = (water_amount / 500.0).ceil
    return bottles
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calculates_controller.rb
class CalculatesController < ApplicationController
  before_action :set_calculate, only: [:show]

  def index
  end

  def new
    @calculate = Calclate.new
  end

  def create
    @calculate = Calclate.new(calculate_params)
    @water_amount = @calculate.calculate_water_amount
    @bottles = @calculate.calculate_water_bottles
      render :show
  end

  def show
  end

  #このクラスでしか使わないメソッドはprivate以下に記述する
  private

  def calculate_params
    params.require(:calclate).permit(:weight, :activity_time)
  end

  def set_calculate
    @calculate = Calclate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculates_helper.rb
module CalculatesHelper
end

app/views/calculates/index.html.erb
<h1>山に行くときの水の量</h1>

<ul>
  <li>
    <p>登山に行く際に必要な水の量を計算するアプリです！</p>
    <p>体重と活動時間を入力すると、必要な水の量を計算します</p>
  </li>
    <div class="button-container">
      <%= link_to "計算する", new_calculate_path, class: "form-button" %>
    </div>
</ul>

app/views/calculates/new.html.erb
<h1>体重と活動時間を入力してください</h1>

<%= form_with model: @calculate, url: calculates_path, html: {class: "form-container"}, validate: true do |form| %>

  <div class="form-input">
    <%= form.label :"体重(Kg)" %><%= form.number_field :weight, in: 1..200, step: 1, required: true %>
  </div>
  <div class="form-input">
    <%= form.label :"活動時間(h)" %><%= form.number_field :activity_time, in: 1..24, step: 1, required: true %>
  </div>
  <div class="button-container">
    <%= form.submit "計算", class: "form-button", disabled: true %>
    <%= link_to "戻る", calculates_path, class: "form-button" %>
  </div>
<% end %>

<script>
  const form = document.querySelector('form');
  const submitButton = form.querySelector('input[type="submit"]');

  form.addEventListener('input', () => {
    const inputs = Array.from(form.elements).filter(input => input.tagName === 'INPUT' && input.required);
    const isFormValid = inputs.every(input => input.checkValidity());
    submitButton.disabled = !isFormValid;
  });
</script>

app/views/calculates/show.html.erb
<h1>計算結果を表示します</h1>

<ul>
  <li>
    <h2>登山に行く際に必要な水の量 <%= @water_amount %>mlです</h2>
    <h2>500mlのペッドボトルを<%= @bottles %>本用意しましょう！ </h2>
  </li>
</ul>

<div class="button-container">
  <%= link_to "戻る", calculates_path, class: "form-button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>